---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/json/curated_categories.json
  label: Curated Categories
  match: "**/*"
- type: document
  path: src/json/explanations.json
  label: Categories
- type: document
  path: src/json/framework_database.json
  label: Frameworks
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
