---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  label: Build Status
  path: NETLIFY.md
  read_only: true
- type: document
  path: src/json/tech-policy-int/site_info.json
  label: Site Information
- type: document
  path: src/json/tech-policy-int/framework_database.json
  label: Frameworks
- type: document
  path: src/json/tech-policy-int/curated_categories.json
  label: Curated Categories
- type: document
  path: src/json/tech-policy-int/explanations.json
  label: Categories
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
